---
# kitchen configuration for CI testing
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service
    - yum -y install net-tools

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  requirements_path: test/requirements-test.yml

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
  - name: fedora-30
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip net-tools
    provisioner:
      require_pip: true
      ansible_cfg_path: test/ansible.cfg
  - name: fedora-31
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip net-tools
    provisioner:
      require_pip: true
      ansible_cfg_path: test/ansible.cfg
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
        - apt-get -y install net-tools
  - name: ubuntu-19.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
        - apt-get -y install net-tools
  - name: debian-8
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: install_archive
    provisioner:
      playbook: test/integration/install/install_archive/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_archive
  - name: config_prometheus
    provisioner:
      playbook: test/integration/config/config_prometheus/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/config_prometheus
  - name: config_rule_files
    provisioner:
      playbook: test/integration/config/rule_files/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/rule_files
  - name: config_file_sd
    provisioner:
      playbook: test/integration/config/file_sd/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/file_sd
  - name: launch_service
    provisioner:
      playbook: test/integration/launch/launch_service/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/launch_service
  - name: setup_alertmanager
    provisioner:
      playbook: test/integration/setup/setup_alertmanager/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/setup/setup_alertmanager
  - name: setup_exporters
    provisioner:
      playbook: test/integration/setup/setup_exporters/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/setup/setup_exporters
