---
- name: Ensure existence of Alertmanager templates directory
  become: true
  file:
    path: "{{ templates_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"

- name: Render Alertmanager templates configuration
  become: true
  template:
    src: "{{ _alertmanager_templates_template }}"
    dest: "{{ templates_path }}/{{ item.name }}.tmpl"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0644
  vars:
    conf: "{{ item.config }}"
  when: item.config is defined and item.config|length > 0
