---
- name: Copy Alertmanager configuration in place
  become: true
  template:
    src: "{{ alertmgr_config_file }}.j2"
    dest: "{{ alertmgr_configdir }}/{{ alertmgr_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0644
    validate: "{{ alertmgr_installdir }}/amtool check-config %s"
  vars:
    conf: "{{ alertmgr_config }}"
  when: alertmgr_config is defined and alertmgr_config.keys()|length > 0

- name: Ensure existence of Alertmanager data dir
  become: true
  file:
    path: "{{ alertmgr_datadir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    state: directory
  when: '"alertmanager" in managed_services'
