---
- name: Copy Prometheus configuration in place
  become: true
  template:
    src: "{{ prometheus_config_file }}.j2"
    dest: "{{ config_dir }}/{{ prometheus_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0644
    validate: "{{ install_dir }}/promtool check config %s"
  vars:
    conf: "{{ prometheus_config }}"
  when: prometheus_config is defined and prometheus_config.keys()|length > 0
