---
- name: Determine configuration directory
  set_fact:
    config_dir: "{{ config_dir | default(install_dir) }}"

- name: Ensure existence of config dir
  become: true
  file:
    path: "{{ config_dir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    state: directory

- name: Copy Prometheus configuration in place
  become: true
  template:
    src: "{{ prometheus_config_file }}.j2"
    dest: "{{ config_dir }}/{{ prometheus_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0644
    validate: "{{ install_dir }}/promtool check config %s"
  vars:
    conf: "{{ config }}"
  when: config is defined and config is not none
