---
- name: Ensure Prometheus system group exists
  become: true
  group:
    name: "{{ prometheus_user }}"
    state: present
    system: true

- name: Create Prometheus system user
  become: true
  user:
    comment: Prometheus service account
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false

- name: perform designated installation procedure
  include_tasks: "common/install/{{ install_type }}_install.yml"
  when: '"prometheus" in managed_services'

- name: perform alertmanager installation procedure
  include_tasks: "common/install/alertmanager_install.yml"
  when: '"alertmanager" in managed_services'

- name: perform exporter installation procedure
  include_tasks: "common/install/exporter_install.yml"
  with_items: "{{ prometheus_exporters }}"
  loop_control:
    loop_var: exporter
  when: prometheus_exporters is defined and prometheus_exporters is not none
