---
- name: Create Prometheus system group
  become: true
  group:
    name: "{{ prometheus_user }}"
    state: present
    system: true

- name: Create Prometheus system user
  become: true
  user:
    comment: Prometheus service account
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false

- name: Install Prometheus based on install type
  include_tasks: "common/install/{{ install_type }}_install.yml"
  when: '"prometheus" in managed_services'

- name: Install Alertmanager
  include_tasks: "common/install/alertmanager_install.yml"
  when: '"alertmanager" in managed_services'

- name: Install Exporters
  include_tasks: "common/install/exporter_install.yml"
  with_items: "{{ prometheus_exporters }}"
  loop_control:
    loop_var: exporter
  when: prometheus_exporters is defined and prometheus_exporters|length > 0
