---
- name: Ensure Prometheus group exists
  group:
    name: "{{ prometheus_user }}"
    state: present
  become: true

- name: Create Prometheus user
  user:
    comment: Prometheus service account
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  become: true

- name: perform designated installation procedure
  include_tasks: "common/install/{{ install_type }}_install.yml"
