---
- name: Create installation directory
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  become: true
  when: 'install_type == "archive" and "prometheus" in managed_services'
  tags:
    - install
    - archive

- name: Download Prometheus archive ({{ archive_url }})
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ checksum_format }}:{{ archive_checksum }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
  register: archive_tmp
  become: true
  when: 'install_type == "archive" and "prometheus" in managed_services'
  tags:
    - install
    - archive

- name: Extract Prometheus archive
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
    creates: "{{ install_dir }}/prometheus"
  become: true
  when: 'install_type == "archive" and "prometheus" in managed_services'
  tags:
    - install
    - archive
